import { Card, CardContent } from '@/components/ui/Card';
import { withBase } from '@/lib/publicUrl';

const INTRO_IMAGES = [
  {
    src: withBase('img/Picture1.png'),
    alt: 'Vidalia onion production field contamination pathways diagram',
  },
  {
    src: withBase('img/Picture2.png'),
    alt: 'Vidalia onion production field risk factors and farm practices diagram',
  },
] as const;

export function IntroductionPage() {
  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-3xl font-bold text-uga-black">
          Food Safety Risk Assessment Tool for Vidalia Onion Production Fields across the Southeastern U. S.
        </h2>
      </div>

      <Card className="overflow-hidden">
        <div className="flex flex-col gap-6 p-4 sm:p-6">
          {INTRO_IMAGES.map((image) => (
            <img
              key={image.src}
              src={image.src}
              alt={image.alt}
              className="h-auto w-full rounded-md border border-uga-card-border object-contain"
            />
          ))}
        </div>
      </Card>

      <Card>
        <CardContent className="space-y-4">
          <div>
            <h3 className="text-lg font-semibold text-uga-black">About this dashboard</h3>
            <p className="mt-1.5 text-lg leading-relaxed text-uga-dark-gray">
              This dashboard is designed to help onion growers and stakeholders evaluate pathogen dynamics across
              different agricultural scenarios. By providing easy-to-use visualization tools, it supports proactive
              decision-making to minimize the risk of fresh onion contamination before harvest.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-uga-black">About this project</h3>
            <div className="mt-1.5 space-y-3 text-lg leading-relaxed text-uga-dark-gray">
              <p>
                Vidalia onions are an economically important specialty crop in the southeastern U. S. Contamination of
                onions by enteric pathogens remains a significant food safety concern for growers, regulators, and
                consumers. Understanding how environmental conditions, agricultural practices, and surrounding land use
                influence contamination risks is critical for improving produce safety.
              </p>
              <p>
                This project aims to develop a science-based risk assessment framework for Vidalia onion production
                fields. The dashboard integrates information from scientific literature, field observations,
                environmental data, and expert knowledge to evaluate factors that may contribute to microbial
                contamination before harvest.
              </p>
              <p>
                Generic Escherichia coli is used as an indicator organism because its presence can reflect environmental
                conditions associated with elevated risks of foodborne pathogens such as Salmonella and E. coli
                O157:H7. By combining multiple risk factors into an interactive assessment platform, the tool helps
                identify scenarios where contamination risks may be increased.
              </p>
              <p>
                The goal of this dashboard is to support growers and industry stakeholders in making informed
                management decisions, prioritizing risk mitigation efforts, and improving the microbial safety of
                fresh Vidalia onions.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="rounded-md border border-l-4 border-uga-card-border border-l-uga-red bg-uga-red/5 p-4">
        <h3 className="text-lg font-semibold text-uga-black">Disclaimer</h3>
        <p className="mt-1.5 text-lg leading-relaxed text-uga-dark-gray">
          This dashboard is intended for research, educational, and decision-support purposes only. Risk estimates
          generated by this tool are based on currently available data, scientific literature, and model assumptions.
          Results should not be interpreted as guarantees of contamination or safety and should not replace regulatory
          requirements, field inspections, or professional food safety assessments. Users are responsible for
          interpreting and applying the information provided by this dashboard.
        </p>
      </div>
    </div>
  );
}
